# starship config file

# set custom format
format = """
[](bold fg:brown bg:background)\
[ ](bold fg:bright-white bg:brown)\
$username\
[](bold fg:burntorange bg:brown)\
[ ](fg:bright-white bg:burntorange)\
$directory\
[](bold fg:mustard bg:burntorange)\
$time\
[](bold fg:mustard bg:background)\
$character\
$cmd_duration\n
[ > ](bold fg:bright-white)\
"""

# set custom color palette
palette = "supergraphic"

# define palette colors
[palettes.supergraphic]
brown = "#a5682b"
burntorange = "#d88313"
mustard = "#f1ab1c"
background = "#282828"

# set custom user print out
[username]
show_always = true
style_user = "fg:bright-white bg:brown"
style_root = "fg:bright-white bg:brown"
format = '[ $user ]($style)'

# set custom working directory display
[directory]
style = "bold bg:burntorange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
home_symbol = "~"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󱉙"
"Music" = "󰲸"
"Pictures" = " "

# set time style
[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "fg:bright-white bg:mustard"
format = '[ $time ]($style)'

# set custom errors shapes and colors
[character]
success_symbol = "[   command run success  ](fg:#a0db15)"
error_symbol = "[   command run failure  ](fg:#d83e2c)"

# set custom cmd duration format
[cmd_duration]
min_time = 0
show_milliseconds = true
style = "fg:bright-white"
format = "[ elapsed time $duration]($style)"